# Problem 1 

In [7]:
# 1 - numpy kütüphanesini import edin

import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun

array = np.random.randint(1, 6, size=5)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.

sorted_array = np.sort(array)

print("Orijinal Array:", array)
print("Sıralanmış Array:", sorted_array)

Orijinal Array: [3 5 1 4 3]
Sıralanmış Array: [1 3 3 4 5]


# Problem 2

In [18]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.

array1 = np.array([10, 15, 30, 45, 60])
print("Array 1:", array1)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.

array2 = np.arange(5, 16)
print("Array 2:", array2)
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.

array3 = np.arange(50, 101, 5)
print("Array 3:", array3)


# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.

array4 = np.zeros(10)
print("Array 4:", array4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.

array5 = np.ones(10)
print("Array 5:", array5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.

array6 = np.linspace(0, 100, 5)
print("Array 6:", array6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.

array7 = np.random.randint(10, 31, 5)
print("Array 7:", array7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.

array8 = np.random.uniform(-1, 1, 10)
print("Array 8:", array8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

matrix9 = np.random.randint(10, 51, (3, 5))
print("Matrix 9:\n", matrix9)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?

row_sums = matrix9.sum(axis=1)
col_sums = matrix9.sum(axis=0)
print("Satır toplamları:", row_sums)
print("Sütun toplamları:", col_sums)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?

max_value = matrix9.max()
min_value = matrix9.min()
mean_value = matrix9.mean()
print("Max değer:", max_value)
print("Min değer:", min_value)
print("Ortalama:", mean_value)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?

max_index = np.unravel_index(np.argmax(matrix9), matrix9.shape)
print("En büyük değerin endeksi:", max_index)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

array13 = np.arange(10, 21)[:3]
print("İlk 3 eleman:", array13)

# 14- Üretilen dizinin elemanlarını tersten yazdırın.

array14 = array13[::-1]
print("Ters array:", array14)

# 15- Üretilen matrisin ilk satırını seçiniz.

first_row = matrix9[0, :]
print("İlk satır:", first_row)

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir?

eleman_2_3 = matrix9[1, 2]
print("İlgili eleman:", eleman_2_3)

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.

first_column = matrix9[:, 0]
print("Tüm satırlardaki ilk eleman:", first_column)

# 18- Üretilen matrisin her bir elemanının karesini alınız.

squared_matrix = np.square(matrix9)
print("Karesi alınmış matris:\n", squared_matrix)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.

matrix19 = np.random.randint(-50, 51, (3, 5))
positive_even_numbers = matrix19[(matrix19 > 0) & (matrix19 % 2 == 0)]
print("Matris:\n", matrix19)
print("Pozitif çift sayılar:", positive_even_numbers)

Array 1: [10 15 30 45 60]
Array 2: [ 5  6  7  8  9 10 11 12 13 14 15]
Array 3: [ 50  55  60  65  70  75  80  85  90  95 100]
Array 4: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array 5: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array 6: [  0.  25.  50.  75. 100.]
Array 7: [25 19 17 22 16]
Array 8: [-0.87399669  0.07823406 -0.02164376  0.79328847 -0.34691783  0.20394183
  0.50881504 -0.17067933  0.72688015  0.24925939]
Matrix 9:
 [[46 10 50 16 34]
 [18 28 16 27 15]
 [47 40 35 19 36]]
Satır toplamları: [156 104 177]
Sütun toplamları: [111  78 101  62  85]
Max değer: 50
Min değer: 10
Ortalama: 29.133333333333333
En büyük değerin endeksi: (np.int64(0), np.int64(2))
İlk 3 eleman: [10 11 12]
Ters array: [12 11 10]
İlk satır: [46 10 50 16 34]
İlgili eleman: 16
Tüm satırlardaki ilk eleman: [46 18 47]
Karesi alınmış matris:
 [[2116  100 2500  256 1156]
 [ 324  784  256  729  225]
 [2209 1600 1225  361 1296]]
Matris:
 [[  7 -36  19 -20  30]
 [ 19 -42 -41  35  -8]
 [ 44 -45 -46  25 -45]]
Pozitif çift sayılar: [30 44]